### PR TITLE
Clean things up and add build checker.

### PR DESCRIPTION
**Pull request by jonthegeek**

### CODE REVIEW

**Comment by jonthegeek** [comment]
@russHyde Wait to make sure the build works. I had to turn off evaluation in a chapter 11 block to get it to build.

Please try to name blocks (even if somewhat random) to make debugging easier!

**Comment by jonthegeek** [comment]
Hmm. {crrri} fails to install. This is the error. Any idea how we might fix this?

```
OE> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
OE>   unable to load shared object '/Users/runner/work/_temp/Library/jsonlite/libs/jsonlite.so':
OE>   dlopen(/Users/runner/work/_temp/Library/jsonlite/libs/jsonlite.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libR.dylib
OE>   Referenced from: /Users/runner/work/_temp/Library/jsonlite/libs/jsonlite.so
OE>   Reason: image not found
```

**Comment by jonthegeek** [comment]
Closes #12.

**Comment by russHyde** [comment]
@jonthegeek  thanks so much for this. We can probably remove {crrri} as a dependency, and turn any code blocks that use it into formatted text

**Pull request merged**
